### ISSUE TITLE
Basel Face Model dependency

### ISSUE THREAD

**Issue by ketz** [FuxiCV/MeInGame#16]
Hello,

I'd love to create something great with this, and make it user-facing, so people could enjoy it.
To cover the development costs of something like that, I'd likely use a brand to cover sponsor of the costs, which would make this a commercial application, I believe.

I saw you have a dependency on the BFM and so I got in touch with them to check the costs to use their face model, and I was quoted EUR 10’000 per year, or a one-time payment of EUR 40'000 for a perpetual license.

Unfortunately those costs make the commercial use of your library prohibitive, so I was wondering if during your research you had considered a cheaper/free alternative to BFM?

Sorry for the odd question, but I love what you built and would love to expand on it.

Best regards

**Comment by Agent-INF** [comment]
Sorry to hear about this, but we have not considered the issue of commercial licenses yet.
As mentioned in our paper, our method can also use other 3DMM models, as long as you can generate a 3D face mesh corresponding to the input portrait.
However, there may be an alternative way, which is to use a free 3D facial landmark detector to replace the 3DMM method, because we end up using the landmark vertices on the 3D face mesh for shape transfer. But we cannot guarantee good results.
Good luck with that!
